# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, width_field='width_field'),
        ),
    ]
