# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_order', '0002_auto_20170306_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_order',
            name='razorpay_order_id',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
