# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppUsers', '0004_auto_20170217_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_amount', models.IntegerField()),
                ('order_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('X', 'Completed')], default='P', max_length=120)),
                ('order_placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsers.AppUser')),
            ],
        ),
    ]
