# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0002_auto_20170217_0009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUsers',
            new_name='AppUser',
        ),
    ]
