# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0003_auto_20170217_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
